from sqlalchemy import Column, Integer, String, Boolean, Numeric, ForeignKey, Enum
from sqlalchemy.orm import relationship
from app.database import Base
from .enums import Species, Gender, Size, EnergyLevel, PetStatus


class Pet(Base):
    __tablename__ = "pet"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    species = Column(Enum(Species, values_callable=lambda e: [i.value for i in e]), nullable=False)
    breed = Column(String, nullable=False)
    age = Column(Numeric(precision=3,scale=1), nullable=False)  # in years
    gender = Column(Enum(Gender, values_callable=lambda e: [i.value for i in e]), nullable=False)
    size = Column(Enum(Size, values_callable=lambda e: [i.value for i in e]), nullable=False)
    energy_level = Column(Enum(EnergyLevel, values_callable=lambda e: [i.value for i in e]), nullable=False)
    description = Column(String, nullable=True)  # generated by AI, starts empty
    photo_url = Column(String, nullable=True)  # filled by file upload service
    adoption_fee = Column(Numeric(10, 2), nullable=True)  # optional contribution/vet-cost fee

    status = Column(Enum(PetStatus, values_callable=lambda e: [i.value for i in e]), nullable=False,
                    default=PetStatus.AVAILABLE)  # available / pending / adopted
    owner_id = Column(Integer, ForeignKey("user.id"), nullable=False)
    category_id = Column(Integer, ForeignKey("category.id"), nullable=False)

    is_approved = Column(Boolean, nullable=False, default=False)  # user listings wait for approval; admin sets to true

    owner = relationship(
        "User",
        back_populates="pets",
    )
    category = relationship(
        "Category",
        back_populates="pets",
    )
